{
 "title": "Hytale Server",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "world",
    "label": "world",
    "query": {
     "query": "label_values(hytale_tps, world)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Player Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hytale_player_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Player Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 0 },
   "targets": [
    { "expr": "hytale_player_count", "legendFormat": "Player Count" }
   ]
  },
  {
   "title": "World \"$world\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "repeat": "world"
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "hytale_tps{world=\"$world\"}",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "hytale_world_entity_count{world=\"$world\"}",
     "legendFormat": "Entities"
    }
   ]
  },
  {
   "title": "Loaded Chunks per 5 Min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(hytale_chunk_generation_total{world=\"$world\"}[5m])",
     "legendFormat": "Loaded Chunks"
    }
   ]
  },
  {
   "title": "Active Chunks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "hytale_world_active_chunks{world=\"$world\"}",
     "legendFormat": "Active Chunks"
    }
   ]
  },
  {
   "title": "Newly generated Chunks per 5 Min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(hytale_chunk_generation_rate_total{world=\"$world\"}[5m])",
     "legendFormat": "Generated Chunks"
    }
   ]
  }
 ]
}