{
 "title": "Hytale Server",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "world",
    "label": "world",
    "query": {
     "query": "label_values(hytale_tps, world)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(jvm_runtime_info, job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_runtime_info, instance)"
    }
   },
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "label_values({__name__=~\"container.*\", instance=~\"$container_host\"},name)"
    }
   },
   {
    "name": "container_host",
    "label": "Container Host",
    "query": {
     "query": "label_values({__name__=~\"container.*\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Misc. Instruments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Metric Health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Player Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hytale_player_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_memory_used_bytes{area=\"nonheap\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_rss{instance=~\"$container_host\",name=~\"$container\",name=~\".+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=~\"$container_host\",name=~\"$container\",name=~\".+\"}[5m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "World \"$world\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "repeat": "world"
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "hytale_tps{world=\"$world\"}",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "Player Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "hytale_player_count", "legendFormat": "Player Count" }
   ]
  },
  {
   "title": "Loaded Chunks per 5 Min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(hytale_chunk_generation_total{world=\"$world\"}[5m])",
     "legendFormat": "Loaded Chunks"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "hytale_world_entity_count{world=\"$world\"}",
     "legendFormat": "Entities"
    }
   ]
  },
  {
   "title": "Active Chunks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "hytale_world_active_chunks{world=\"$world\"}",
     "legendFormat": "Active Chunks"
    }
   ]
  },
  {
   "title": "Newly generated Chunks per 5 Min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(hytale_chunk_generation_rate_total{world=\"$world\"}[5m])",
     "legendFormat": "Generated Chunks"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\", job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Used Heap Memory"
    },
    {
     "expr": "jvm_memory_used_bytes{area=\"nonheap\", job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Used Non-Heap Memory"
    },
    {
     "expr": "jvm_memory_max_bytes{area=\"heap\", job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Max heap memory"
    },
    {
     "expr": "jvm_memory_max_bytes{area=\"nonheap\", job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Max non heap memory"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Current Threads"
    },
    {
     "expr": "jvm_threads_daemon{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Daemon Threads"
    },
    {
     "expr": "jvm_threads_deadlocked{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Deadlocked Threads"
    }
   ]
  },
  { "title": "CAdvisor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=~\"$container_host\",name=~\"$container\",name=~\".+\"}[5m]) * 100",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_rss{instance=~\"$container_host\",name=~\"$container\",name=~\".+\"}",
     "legendFormat": "Memory Usage"
    }
   ]
  }
 ]
}